name:        fsnotify-conduit
version:     0.1.1.0
synopsis:    Get filesystem notifications as a stream of events
description: Please see README.md
description: Please see the README and docs at <https://www.stackage.org/package/fsnotify-conduit>
category:    Data, Conduit
author:      Michael Snoyman
maintainer:  michael@snoyman.com
copyright:   2016-2018 FP Complete
license:     MIT
github:      fpco/fsnotify-conduit

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4.9 && <5
- conduit >=1.2.8
- directory
- filepath
- fsnotify >=0.2.1
- resourcet
- transformers

library:
  source-dirs: src

tests:
  fsnotify-conduit-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fsnotify-conduit
    - hspec
    - temporary
